# Configuration constants
MIN_USERNAME_LENGTH = 4
MAX_USERNAME_LENGTH = 10
MIN_PASSWORD_LENGTH = 4
MAX_PASSWORD_LENGTH = 10
ALLOWED_USERNAME_CHARS = set('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-')
ALLOWED_PASSWORD_CHARS = set('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-')
